### PR TITLE
Refactor SignUpPage

### PR DESCRIPTION
**Pull request by Wallert**
Removed extra spaces and functions

### CODE REVIEW

**Review by dazeforlife — COMMENTED** [review]
Nice!

**Review by Sarhsian — COMMENTED** [review]
delete empty stroke 6

**Review by Sarhsian — COMMENTED** [review]
good

**Review by vadymhrnk — COMMENTED** [review]
Ok

**Review by MishkaBaloo — COMMENTED** [review]
Gj

**Pull request merged**
